# Generated by Django 4.2.10 on 2025-03-31 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_enrollment_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='status')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='data de pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='método de pagamento')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID da transação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.enrollment', verbose_name='matrícula')),
            ],
            options={
                'verbose_name': 'transação de pagamento',
                'verbose_name_plural': 'transações de pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
