# Generated by Django 4.2.10 on 2025-03-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='brcode',
            field=models.TextField(blank=True, help_text='Código Pix copia e cola', null=True, verbose_name='BR Code Pix'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='correlation_id',
            field=models.CharField(blank=True, help_text='ID de correlação para pagamentos via Pix', max_length=255, verbose_name='ID de Correlação'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='qrcode_image',
            field=models.URLField(blank=True, help_text='URL da imagem do QR Code para pagamento Pix', null=True, verbose_name='URL do QR Code'),
        ),
    ]
