# Generated by Django 4.2.10 on 2025-04-05 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_paymenttransaction_brcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('REFUNDED', 'Estornado'), ('FAILED', 'Falhou')], default='PENDING', max_length=10, verbose_name='Status')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Email do Cliente')),
                ('customer_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('payment_method', models.CharField(default='pix', max_length=20, verbose_name='Método de Pagamento')),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Correlação')),
                ('brcode', models.TextField(blank=True, null=True, verbose_name='BR Code')),
                ('qrcode_image', models.TextField(blank=True, null=True, verbose_name='QR Code (imagem)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda Avulsa',
                'verbose_name_plural': 'Vendas Avulsas',
                'ordering': ['-created_at'],
            },
        ),
    ]
