# Generated by Django 4.2.10 on 2025-03-31 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('processing', 'Processando'), ('approved', 'Aprovada'), ('cancelled', 'Cancelada'), ('error', 'Erro')], default='draft', max_length=20, verbose_name='status')),
                ('focus_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID no Focus')),
                ('focus_url', models.URLField(blank=True, null=True, verbose_name='URL no Focus')),
                ('focus_pdf_url', models.URLField(blank=True, null=True, verbose_name='URL do PDF')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='dados da resposta')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='mensagem de erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('emitted_at', models.DateTimeField(blank=True, null=True, verbose_name='emitido em')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.paymenttransaction', verbose_name='transação')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='habilitar emissão de nota')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome fantasia')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='endereço')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='bairro')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, null=True, verbose_name='inscrição municipal')),
                ('regime_tributario', models.CharField(choices=[('simples', 'Simples Nacional'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], default='simples', max_length=20, verbose_name='regime tributário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_config', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'configuração da empresa',
                'verbose_name_plural': 'configurações da empresa',
            },
        ),
    ]
