# Generated by Django 4.2.10 on 2025-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_companyconfig_regime_tributario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='focus_data',
            field=models.TextField(blank=True, null=True, verbose_name='Dados completos do Focus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='focus_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem do Focus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='focus_reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência no Focus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='focus_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status no Focus'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='focus_xml_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do XML'),
        ),
    ]
