# Generated by Django 4.2.10 on 2025-03-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_focus_data_invoice_focus_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID externo API'),
        ),
    ]
