# Generated by Django 4.2.10 on 2025-03-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_rps_fields'),
        ('invoices', '0004_invoice_external_id'),
    ]

    operations = [
    ]
