# Generated by Django 4.2.10 on 2025-04-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.PositiveIntegerField(default=0, help_text='Posição atual em segundos de onde o aluno parou de assistir', verbose_name='posição atual (segundos)')),
                ('video_duration', models.PositiveIntegerField(default=0, help_text='Duração total do vídeo em segundos', verbose_name='duração total (segundos)')),
                ('watched_percentage', models.PositiveIntegerField(default=0, help_text='Porcentagem do vídeo que foi assistida (0-100)', verbose_name='porcentagem assistida')),
                ('watched_segments', models.JSONField(blank=True, help_text='Registra os segmentos do vídeo já assistidos pelo aluno', null=True, verbose_name='segmentos assistidos')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='última atualização')),
                ('lesson_progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='courses.lessonprogress', verbose_name='progresso da aula')),
            ],
            options={
                'verbose_name': 'progresso de vídeo',
                'verbose_name_plural': 'progressos de vídeos',
            },
        ),
    ]
