# Generated by Django 4.2.10 on 2025-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada'), ('PENDING', 'Pendente')], default='ACTIVE', max_length=10, verbose_name='status'),
        ),
    ]
