# Generated by Django 4.2.10 on 2025-03-31 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('system_prompt', models.TextField(help_text="Instruções que definem o comportamento do assistente. Este texto funcionará como um 'prompt de sistema' para o modelo de IA.", verbose_name='Orientações de comportamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_behaviors', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Comportamento do Assistente',
                'verbose_name_plural': 'Comportamentos do Assistente',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
