# Generated by Django 4.2.10 on 2025-03-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Regra de recorrência'),
        ),
    ]
