# Generated by Django 4.2.10 on 2025-03-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_event_recurrence_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlocation',
            options={'ordering': ['name'], 'verbose_name': 'Estúdio', 'verbose_name_plural': 'Estúdios'},
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do estúdio'),
        ),
    ]
