# Generated by Django 4.2.10 on 2025-04-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_eventlocation_options_alter_eventlocation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contato da unidade', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem da unidade', null=True, upload_to='studios/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone de contato da unidade', max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço físico do estúdio (caso não seja online)', null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este estúdio sem excluí-lo', verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Marque esta opção se for um estúdio virtual/online', verbose_name='Online?'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link da sala virtual (Zoom, Meet, etc.)', null=True, verbose_name='Link da reunião'),
        ),
    ]
