# Generated by Django 4.2.10 on 2025-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_eventlocation_email_eventlocation_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlocation',
            options={'ordering': ['name'], 'verbose_name': 'Local de Evento', 'verbose_name_plural': 'Locais de Eventos'},
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Capacidade'),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(blank=True, help_text='Endereço completo do estúdio', max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Marque esta opção se for um estúdio virtual', verbose_name='É online?'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link para acesso à aula/ensaio virtual (Zoom, Google Meet, etc)', null=True, verbose_name='Link de reunião'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
