# Generated by Django 4.2.10 on 2025-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_eventlocation_options_eventlocation_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlocation',
            options={'ordering': ['name'], 'verbose_name': 'Estúdio', 'verbose_name_plural': 'Estúdios'},
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='eventlocation',
            name='description',
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço físico do estúdio (caso não seja online)', null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Marque esta opção se for um estúdio virtual/online', verbose_name='Online?'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link da sala virtual (Zoom, Meet, etc.)', null=True, verbose_name='Link da reunião'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do estúdio'),
        ),
    ]
